/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Auction API
 * API documentation for Auction application
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import * as axios from 'axios';

/**
 * Login request containing user credentials
 */
export interface LoginRequest {
  /** Username */
  username: string;
  /** Password */
  password: string;
}

/**
 * Login response containing access token and user information
 */
export interface LoginResponse {
  /** JWT access token */
  access_token?: string;
  /** Token expiration time in seconds */
  expires_in?: number;
  /** Refresh token expiration time in seconds */
  refresh_expires_in?: number;
  /** Refresh token */
  refresh_token?: string;
  /** Token type (Bearer) */
  token_type?: string;
  /** Not before policy */
  'not-before-policy'?: number;
  /** Session state */
  session_state?: string;
  /** Token scope */
  scope?: string;
}

export interface UserProfileView {
  userId?: string;
  email?: string;
  username?: string;
  fullName?: string;
  preferredLanguage?: string;
}

export interface GenericApiResponseUserProfileView {
  success?: boolean;
  message?: string;
  data?: UserProfileView;
  error?: unknown;
  timestamp?: string;
  statusCode?: number;
}

/**
 * Authenticate user with username and password via Keycloak and return JWT token
 * @summary User login
 */
export const login = <TData = AxiosResponse<LoginResponse>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/v1/auth/login`, loginRequest, options);
};

/**
 * Retrieves the profile of the currently authenticated user
 * @summary Get current user profile
 */
export const getCurrentUser = <TData = AxiosResponse<Blob>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/v1/users/me`, {
    responseType: 'blob',
    ...options,
  });
};

export type LoginResult = AxiosResponse<LoginResponse>;
export type GetCurrentUserResult = AxiosResponse<Blob>;
